import { Bot, CheckCircle2, Database, Radio, ShieldCheck } from "lucide-react";

export function RealTimeBadge({ mode = "LIVE" }: { mode?: "LIVE" | "CACHED" | "SIMULATED" }) {
  const color = mode === "LIVE" ? "bg-emerald-400" : mode === "CACHED" ? "bg-amber-400" : "bg-slate-400";
  return (
    <span className="inline-flex items-center gap-2 rounded-md border border-line bg-ink px-2 py-1 text-xs font-semibold">
      <span className={`h-2 w-2 rounded-full ${color} ${mode === "LIVE" ? "animate-pulse" : ""}`} />
      {mode}
    </span>
  );
}

export function TensorFlowStatus({ ready, status }: { ready: boolean; status: string }) {
  return (
    <span className="inline-flex items-center gap-2 rounded-md border border-line bg-ink px-2 py-1 text-xs">
      <Radio className="h-3.5 w-3.5 text-accent" />
      {ready ? "TF.js Ready" : status || "Loading ML models..."}
    </span>
  );
}

export function BlockchainBadge({ tx_hash }: { tx_hash?: string | null }) {
  if (!tx_hash) return <span className="text-xs text-slate-400">No confirmed tx</span>;
  return (
    <a className="inline-flex items-center gap-2 text-xs text-accent underline" href={`https://sepolia.etherscan.io/tx/${tx_hash}`} target="_blank" rel="noreferrer">
      <CheckCircle2 className="h-3.5 w-3.5" />
      {tx_hash.slice(0, 10)}...{tx_hash.slice(-6)}
    </a>
  );
}

export function AIBadge({ model = "claude-sonnet-4-5" }: { model?: string }) {
  return (
    <span className="inline-flex items-center gap-2 rounded-md border border-line bg-ink px-2 py-1 text-xs">
      <Bot className="h-3.5 w-3.5 text-accent" />
      Generated by {model}
    </span>
  );
}

export function FirestoreBadge() {
  return (
    <span className="inline-flex items-center gap-2 rounded-md border border-line bg-ink px-2 py-1 text-xs">
      <Database className="h-3.5 w-3.5 text-amber-300" />
      Firestore persisted
    </span>
  );
}

export function AegisMark() {
  return (
    <div className="flex items-center gap-3">
      <span className="grid h-10 w-10 place-items-center rounded-lg bg-accent text-ink">
        <ShieldCheck className="h-6 w-6" />
      </span>
      <div>
        <p className="text-lg font-black tracking-wide">AEGIS v2</p>
        <p className="text-xs text-slate-400">IP Protection + CTI</p>
      </div>
    </div>
  );
}
